### ISSUE TITLE
PyPi

### ISSUE THREAD

**Issue by scrgiorgio** [imjoy-team/imjoy-jupyterlab-extension#6]
Should I see a version of `imjoy-jupyterlab-extension` on PyPi (for JupyterLab 4/itkwidgets[lab] compatible installation)?

it should be version 0.1.21 but I do not see it on Pypi (ref https://pypi.org/project/imjoy-jupyterlab-extension/#history).
thanks

**Comment by oeway** [comment]
Hi @scrgiorgio Thanks for reaching out, I ended up remove the new release since there is a bug after I publishing it. The automatic upgrade script from jupyterlab didn't work well, and the extension does not work as expected. I need some more time to get back to the extension, super busy right now, sorry.

**Comment by scrgiorgio** [comment]
Thanks for the clarification

**Comment by oeway** [comment]
@scrgiorgio

FYI: Jupyterlab 4 is supported with the new release: https://pypi.org/project/imjoy-jupyterlab-extension/
